# Generated by Django 4.0.4 on 2022-05-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rg',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
